Repository ita-social-projects/what-front, pull requests merged in 2020-11, with the labels that each got.

#26 Bootstrap added
  package-lock.json
  package.json
  src/index.js
  src/index.scss
  webpack.config.js
Labels: enhancement, ready to code review

#12 added new readme
  README.md
Labels: documentation

#33 Group starting layout added
  src/app.js
  src/features/counter/counter.js
  src/features/index.js
  src/features/start-group/index.js
  src/features/start-group/start-group.js
  src/index.scss
Labels: Ready to Merge, enhancement, ready to code review

#35 Group editing layout added
  src/features/edit-group/edit-group.js
  src/features/edit-group/index.js
  src/features/index.js
Labels: Ready to Merge, enhancement, ready to code review

#34 Student profile layout
  package-lock.json
  package.json
  src/features/index.js
  src/features/student-profile/index.js
  src/features/student-profile/student-profile.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#16 Static analyzer added
  .eslintrc.js
  package-lock.json
  package.json
Labels: Ready to Merge

#46 Validation form example
  package-lock.json
  package.json
  src/features/validation/form-example.js
  src/features/validation/index.js
  src/features/validation/validation-helpers.js
Labels: Ready to Merge, enhancement, ready to code review

#48 Drozdov 18 authorization layout
  src/features/auth/auth.js
  src/features/auth/auth.module.scss
  src/features/auth/index.js
  src/features/index.js
Labels: ready to code review

#47 Created modal window
  .eslintrc.js
  .gitignore
  src/app.js
  src/features/counter/counter.js
  src/features/modal-window/index.js
  src/features/modal-window/modal-window.js
  src/features/modal-window/modal-window.module.scss
  src/index.html
  src/index.scss
  src/styles/_variables.scss
  src/styles/empty-file.txt
  webpack.config.js
Labels: Ready to Merge, enhancement, ready to code review

#52 Header layout is created
  src/features/header/header.js
  src/features/header/header.module.scss
  src/features/header/index.js
Labels: Change Request, enhancement

#15 Added CSS-modules
  .babelrc
  package-lock.json
  package.json
  postcss.config.js
  src/features/counter/button.scss
  src/features/counter/counter.js
  src/styles/_color-palette.scss
  src/styles/_helpers.scss
  src/styles/_scrollbar.scss
  src/styles/_sizes.scss
  src/styles/_theme.scss
  src/styles/_z-index.scss
  src/styles/main.scss
  webpack.config.js
Labels: Ready to Merge, enhancement, ready to code review

#14 add svg support
  package-lock.json
  package.json
  src/app.js
  src/icon.js
  src/svg/Edit.svg
  src/svg/Plus.svg
  webpack.config.js
Labels: Ready to Merge, Resolve Conflicts, question, ready to code review

#62 feat: layout for group details
  src/components/group-details/group-details.js
  src/components/group-details/index.js
Labels: Ready to Merge, Resolve Conflicts, ready to code review

#63 Add reusable button
  package.json
  src/app.js
  src/components/Button/button.js
  src/components/Button/button.module.scss
  src/components/Button/index.js
  src/components/empty-file.txt
  src/components/index.js
  src/features/counter/counter.js
  src/index.html
Labels: Ready to Merge, enhancement, ready to code review

#79 Fedotova 54 add lesson
  package-lock.json
  package.json
  src/app.js
  src/features/add-lesson/add-lesson.js
  src/features/add-lesson/add-lesson.module.scss
  src/features/add-lesson/index.js
  src/index.html
  src/index.js
  src/index.scss
  src/styles/_helpers.scss
Labels: Change Request, enhancement, ready to code review

#73 Fixed student profile layout
  src/features/student-profile/student-profile.js
  src/features/student-profile/student-profile.scss
Labels: Ready to Merge, enhancement

#85 Drozdov 57 edit students details layout
  src/features/auth/auth.js
  src/features/auth/auth.scss
  src/features/edit-students-details/edit-students-details.js
  src/features/edit-students-details/edit-students-details.scss
  src/features/edit-students-details/index.js
  src/features/index.js
  src/index.html
Labels: 3 points, enhancement, ready to code review

#80 Search input component
  src/components/button/button.js
  src/components/button/button.scss
  src/components/button/index.js
  src/components/index.js
  src/components/search/index.js
  src/components/search/search.js
  src/components/search/search.scss
  src/features/counter/counter.js
  src/features/group-details/group-details.js
  src/features/group-details/index.js
  src/features/modal-window/modal-window.js
  src/features/modal-window/modal-window.scss
  src/icon.js
  src/svg/Search.svg
Labels: enhancement, ready to code review

#87 edit lesson added
  src/app.js
  src/features/add-lesson/add-lesson.js
  src/features/add-lesson/add-lesson.scss
  src/features/edit-lesson/edit-lesson.js
  src/features/edit-lesson/edit-lesson.scss
  src/features/edit-lesson/index.js
Labels: Ready to Merge, enhancement, ready to code review

#72 Card Reusable Component
  package-lock.json
  src/app.js
  src/components/card/card.js
  src/components/card/card.scss
  src/components/card/index.js
  src/components/index.js
  src/icon.js
  src/index.js
  src/styles/_helpers.scss
  src/styles/_variables.scss
  src/svg/Edit.svg
  webpack.config.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#98 fix icon component
  src/app.js
  src/icon.js
  src/svg/Edit.svg
  src/svg/Plus.svg
Labels: Ready to Merge, Resolve Conflicts

#69 Fixed header layout
  src/features/header/header.js
  src/features/header/header.module.scss
  src/features/header/header.scss
  src/features/header/index.js
  src/features/index.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#113 schedule layout
  src/app.js
  src/features/index.js
  src/features/schedule-student/index.js
  src/features/schedule-student/scheduale.js
  src/features/schedule-student/scheduale.scss
Labels: Ready to Merge, ready to code review

#107 Edit search component
  src/components/search/search.js
  src/components/search/search.scss
Labels: Ready to Merge, enhancement

#78 Add icons
  package-lock.json
  package.json
  postcss.config.js
  src/index.js
  src/svg/Back.svg
  src/svg/Calendar.svg
  src/svg/CheckFalse.svg
  src/svg/CheckNull.svg
  src/svg/CheckTrue.svg
  src/svg/CheckboxFalse.svg
  src/svg/CheckboxNull.svg
  src/svg/CheckboxTrue.svg
  src/svg/CloseButton.svg
  src/svg/DropDown.svg
  src/svg/DropDownButton.svg
  src/svg/LogOut.svg
  src/svg/Menu.svg
  src/svg/Profile.svg
  src/svg/Search.svg
Labels: Ready to Merge, enhancement, ready to code review

#122 Fedotova 89 student's list
  src/app.js
  src/components/card/card.scss
  src/components/index.js
  src/components/search/search.js
  src/features/index.js
  src/features/list-of-students/index.js
  src/features/list-of-students/list-of-students.js
  src/features/list-of-students/list-of-students.scss
  src/features/list-of-students/redux/action-types.js
  src/features/list-of-students/redux/actions.js
  src/features/list-of-students/redux/index.js
  src/features/list-of-students/redux/reducer.js
  src/features/list-of-students/redux/selectors.js
  src/features/list-of-students/students-data-list.js
  src/reducer.js
  src/styles/_helpers.scss
  src/styles/_variables.scss
Labels: Ready to Merge, enhancement, ready to code review

#106 List of Groups Feature
  src/app.js
  src/components/card/card.js
  src/components/card/card.scss
  src/components/search/search.js
  src/components/search/search.scss
  src/features/edit-students-details/edit-students-details.js
  src/features/index.js
  src/features/list-of-groups/groups.js
  src/features/list-of-groups/index.js
  src/features/list-of-groups/list-of-groups.js
  src/features/list-of-groups/list-of-groups.scss
  src/features/list-of-groups/redux/action-types.js
  src/features/list-of-groups/redux/actions.js
  src/features/list-of-groups/redux/index.js
  src/features/list-of-groups/redux/reducer.js
  src/features/list-of-groups/redux/selectors.js
  src/reducer.js
  src/shared/hooks/use-actions.js
  src/styles/_variables.scss
Labels: Ready to Merge, ready to code review

#148 change svg files
  src/app.js
  src/icon.js
  src/svg/Back.svg
  src/svg/Calendar.svg
  src/svg/CheckFalse.svg
  src/svg/CheckNull.svg
  src/svg/CheckTrue.svg
  src/svg/CheckboxFalse.svg
  src/svg/CheckboxNull.svg
  src/svg/CheckboxTrue.svg
  src/svg/CloseButton.svg
  src/svg/DropDown.svg
  src/svg/DropDownButton.svg
  src/svg/Menu.svg
  src/svg/Profile.svg
  src/svg/Search.svg
Labels: ready to code review

#86 Tabs reusable component
  src/app.js
  src/components/Tab/index.js
  src/components/Tab/tab.js
  src/components/Tab/tab.scss
  src/components/Tabs/index.js
  src/components/Tabs/tabs.js
  src/components/card/card.scss
  src/components/index.js
  src/components/search/search.js
  src/features/edit-group/edit-group.js
  src/features/edit-lesson/edit-lesson.js
  src/features/index.js
  src/styles/_color-palette.scss
  src/styles/_helpers.scss
  src/styles/_variables.scss
Labels: Ready to Merge, enhancement, ready to code review

#154 Rusynov 5 webpack config
  .babelrc
  .eslintignore
  .eslintrc.js
  config/paths.js
  config/webpack.common.js
  config/webpack.dev.js
  config/webpack.prod.js
  jsconfig.json
  package-lock.json
  package.json
  src/assets/svg/Back.svg
  src/assets/svg/Calendar.svg
  src/assets/svg/CheckFalse.svg
  src/assets/svg/CheckNull.svg
  src/assets/svg/CheckTrue.svg
  src/assets/svg/CheckboxFalse.svg
  src/assets/svg/CheckboxNull.svg
  src/assets/svg/CheckboxTrue.svg
  src/assets/svg/CloseButton.svg
  src/assets/svg/DropDown.svg
  src/assets/svg/DropDownButton.svg
  src/assets/svg/Edit.svg
  src/assets/svg/LogOut.svg
  src/assets/svg/Menu.svg
  src/assets/svg/Plus.svg
  src/assets/svg/Profile.svg
  src/assets/svg/Search.svg
  src/icon.js
  src/index.js
  src/index.scss
  webpack.config.js
Labels: Ready to Merge, Resolve Conflicts, ready to code review

#162 Upgrade haeder layout
  src/components/card/card.scss
  src/features/header/header.js
  src/features/header/header.scss
  src/features/student-profile/student-profile.js
Labels: Ready to Merge, enhancement, ready to code review

#109 Drozdov 77 add routing
  package-lock.json
  package.json
  src/app.js
  src/features/auth/auth.js
  src/features/index.js
  src/features/routes/helpers.js
  src/features/routes/index.js
  src/features/routes/routes.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#149 List of courses Feature
  src/features/index.js
  src/features/list-of-courses/courses-data-list.js
  src/features/list-of-courses/index.js
  src/features/list-of-courses/list-of-courses.js
  src/features/list-of-courses/list-of-courses.scss
Labels: enhancement, ready to code review

#166 Group editing feature
  src/features/edit-group/edit-group.js
  src/features/edit-group/edit-groups.scss
  src/features/edit-group/index.js
  src/features/validation/validation-helpers.js
Labels: Ready to Merge, enhancement, ready to code review

#164 Edit Student`S Details
  package-lock.json
  package.json
  src/components/card/card.js
  src/features/edit-students-details/edit-students-details.js
  src/features/edit-students-details/edit-students-details.scss
  src/features/list-of-students/redux/action-types.js
  src/features/list-of-students/redux/actions.js
  src/features/validation/form-example.js
Labels: Ready to Merge, Resolve Conflicts, ready to code review

#151 Drozdov 145 list of secretaries
  src/app.js
  src/components/card/card.scss
  src/features/index.js
  src/features/list-of-groups/list-of-groups.js
  src/features/list-of-secretaries/index.js
  src/features/list-of-secretaries/list-of-secretaries.js
  src/features/list-of-secretaries/list-of-secretaries.scss
  src/features/list-of-secretaries/redux/action-types.js
  src/features/list-of-secretaries/redux/actions.js
  src/features/list-of-secretaries/redux/index.js
  src/features/list-of-secretaries/redux/reducer.js
  src/features/list-of-secretaries/redux/selectors.js
  src/features/list-of-secretaries/secretariesData.js
  src/features/list-of-students/list-of-students.js
  src/reducer.js
Labels: Ready to Merge, enhancement, ready to code review

#153 Set up saga
  package-lock.json
  package.json
  src/app.js
  src/components/card/card.scss
  src/features/counter/counter.js
  src/features/counter/index.js
  src/features/counter/redux/action-types.js
  src/features/counter/redux/actions.js
  src/features/counter/redux/heplers.js
  src/features/counter/redux/index.js
  src/features/counter/redux/reducer.js
  src/features/counter/redux/sagas.js
  src/features/counter/redux/selectors.js
  src/root-saga.js
  src/store.js
Labels: Ready to Merge, enhancement, ready to code review
