Repository ita-social-projects/what-front, pull requests merged in 2020-12, with the labels that each got.

#170 Add withloader component
  package-lock.json
  src/components/button/button.js
  src/components/index.js
  src/components/with-loading/index.js
  src/components/with-loading/with-loading.js
  src/features/counter/counter.js
  src/features/modal-window/modal-window.js
Labels: enhancement, ready to code review

#169 feat: add deploy script
  package-lock.json
  package.json
Labels: ready to code review

#160 Added api service
  src/app.js
  src/features/counter/counter.js
  src/features/counter/redux/helpers.js
  src/features/counter/redux/sagas.js
  src/models/api-service/api-service.js
  src/models/api-service/config.js
  src/models/api-service/index.js
  src/models/api-service/interceptors.js
  src/models/empty
  src/models/index.js
  src/models/mentors/action-types.js
  src/models/mentors/actions.js
  src/models/mentors/index.js
  src/models/mentors/reducer.js
  src/models/mentors/sagas.js
  src/models/mentors/selectors.js
  src/reducer.js
  src/root-saga.js
  src/shared/index.js
  src/utils/empty-file.txt
  src/utils/helpers/helpers.js
  src/utils/helpers/index.js
  src/utils/index.js
Labels: Ready to Merge, enhancement, ready to code review

#184 Edit mentor form
  src/app.js
  src/features/edit-mentor/edit-mentor.js
  src/features/edit-mentor/edit-mentor.scss
  src/features/edit-mentor/index.js
  src/features/validation/validation-helpers.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#167 Fedotova 136 list of lessons
  src/app.js
  src/components/index.js
  src/features/add-lesson/add-lesson.js
  src/features/edit-lesson/edit-lesson.js
  src/features/index.js
  src/features/list-of-lessons/index.js
  src/features/list-of-lessons/lessons-dataList.js
  src/features/list-of-lessons/list-of-lessons.js
  src/features/list-of-lessons/list-of-lessons.scss
  src/features/list-of-students/list-of-students.js
  src/features/list-of-students/students-dataList.js
  src/reducer.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#185 Drozdov 147 edit secretarys details
  src/app.js
  src/components/index.js
  src/features/edit-secretarys-details/edit-secretarys-details.js
  src/features/edit-secretarys-details/edit-secretarys-details.scss
  src/features/edit-secretarys-details/index.js
  src/features/index.js
  src/features/validation/validation-helpers.js
  src/index.js
Labels: enhancement

#187 Courses model
  src/components/index.js
  src/models/api-service/config.js
  src/models/courses/actions.js
  src/models/courses/index.js
  src/models/courses/reducer.js
  src/models/courses/selectors.js
  src/models/courses/types.js
  src/models/index.js
  src/reducer.js
  src/root-saga.js
  src/shared/api-service/api-service.js
  src/shared/api-service/config.js
  src/shared/api-service/index.js
  src/shared/api-service/interceptors.js
  src/shared/index.js
Labels: Ready to Merge, enhancement, ready to code review

#188 Themes model
  src/components/index.js
  src/models/index.js
  src/models/themes/actions.js
  src/models/themes/index.js
  src/models/themes/reducer.js
  src/models/themes/selectors.js
  src/models/themes/types.js
  src/reducer.js
  src/root-saga.js
Labels: Ready to Merge, enhancement, ready to code review

#190 Schedules model
  src/models/index.js
  src/models/schedules/actions.js
  src/models/schedules/index.js
  src/models/schedules/reducer.js
  src/models/schedules/selectors.js
  src/models/schedules/types.js
  src/reducer.js
  src/root-saga.js
Labels: Ready to Merge, enhancement, ready to code review

#193 Mentors model added
  src/features/counter/counter.js
  src/models/index.js
  src/models/mentors/action-types.js
  src/models/mentors/actions.js
  src/models/mentors/helper-functions.js
  src/models/mentors/index.js
  src/models/mentors/reducer.js
  src/models/mentors/sagas.js
  src/models/mentors/selectors.js
  src/models/mentors/types.js
  src/reducer.js
  src/root-saga.js
  src/shared/api-service/config.js
  src/shared/api-service/interceptors.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#191 Students model
  src/features/counter/counter.js
  src/models/index.js
  src/models/mentors/actions.js
  src/models/mentors/sagas.js
  src/models/students/action-types.js
  src/models/students/actions.js
  src/models/students/index.js
  src/models/students/reducer.js
  src/models/students/reducers/active-students-reducer.js
  src/models/students/reducers/all-students-reducer.js
  src/models/students/reducers/current-student-groups-reducer.js
  src/models/students/reducers/current-student-reducer.js
  src/models/students/reducers/index.js
  src/models/students/selectors.js
  src/reducer.js
  src/root-saga.js
  src/shared/api-service/config.js
Labels: Ready to Merge, enhancement, ready to code review

#189 Lesson Model
  package-lock.json
  src/models/index.js
  src/models/lessons/action-types.js
  src/models/lessons/actions.js
  src/models/lessons/index.js
  src/models/lessons/reducer.js
  src/models/lessons/selectors.js
  src/reducer.js
  src/root-saga.js
  src/shared/api-service/interceptors.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#194 Pasternak 175 accounts model
  .eslintrc.js
  src/features/add-lesson/add-lesson.js
  src/features/add-lesson/index.js
  src/features/counter/counter.js
  src/features/counter/redux/reducer.js
  src/features/edit-group/index.js
  src/features/group-details/group-details.js
  src/features/header/header.js
  src/features/header/index.js
  src/features/start-group/index.js
  src/features/start-group/start-group.js
  src/features/student-profile/student-profile.js
  src/features/support/index.js
  src/features/support/support.js
  src/features/validation/form-example.js
  src/models/account/actions.js
  src/models/account/index.js
  src/models/account/reducer.js
  src/models/account/reducers/index.js
  src/models/account/reducers/login-reducer.js
  src/models/account/reducers/unassigned-reducer.js
  src/models/account/reducers/user-list-reducer.js
  src/models/account/sagas.js
  src/models/account/selectors.js
  src/models/account/types.js
  src/models/api-service/config.js
  src/models/index.js
  src/reducer.js
  src/root-saga.js
  src/shared/api-service/interceptors.js
  src/shared/hooks/index.js
  src/shared/hooks/use-actions.js
  src/utils/helpers/helpers.js
  src/utils/helpers/index.js
  src/utils/index.js
Labels: Ready to Merge, Resolve Conflicts, ready to code review

#199 Connect students list to model
  src/components/card/card.js
  src/components/search/search.scss
  src/components/with-loading/with-loading.js
  src/features/counter/counter.js
  src/features/list-of-students/list-of-students.js
  src/features/list-of-students/list-of-students.scss
  src/features/list-of-students/redux/action-types.js
  src/features/list-of-students/redux/actions.js
  src/features/list-of-students/students-dataList.js
  src/features/routes/routes.js
  src/models/account/index.js
  src/models/account/sagas.js
  src/models/api-service/config.js
  src/models/index.js
  src/reducer.js
  src/root-saga.js
  src/shared/api-service/interceptors.js
Labels: Ready to Merge, enhancement, ready to code review

#196 Drozdov 180 secretaries model
  src/models/index.js
  src/models/secretary/action-types.js
  src/models/secretary/actions.js
  src/models/secretary/index.js
  src/models/secretary/reducer.js
  src/models/secretary/selectors.js
  src/reducer.js
  src/root-saga.js
Labels: enhancement

#217 feat: student-group model
  src/models/index.js
  src/models/student-groups/action-types.js
  src/models/student-groups/actions.js
  src/models/student-groups/index.js
  src/models/student-groups/reducer.js
  src/models/student-groups/selector.js
  src/reducer.js
  src/root-saga.js
Labels: enhancement, ready to code review

#216 Add course feature
  src/features/add-course/add-course.js
  src/features/add-course/add-course.scss
  src/features/add-course/index.js
  src/features/add-lesson/add-lesson.scss
  src/features/edit-lesson/edit-lesson.scss
  src/features/header/header.js
  src/features/index.js
  src/features/list-of-courses/courses-data-list.js
  src/features/list-of-courses/list-of-courses.js
  src/features/routes/routes.js
  src/features/validation/validation-helpers.js
Labels: enhancement, ready to code review

#215 Edit course feature
  src/components/card/card.js
  src/components/card/card.scss
  src/features/edit-course/edit-course.js
  src/features/edit-course/edit-course.scss
  src/features/edit-course/index.js
  src/features/edit-group/edit-group.js
  src/features/edit-lesson/edit-lesson.js
  src/features/index.js
  src/features/list-of-courses/list-of-courses.js
  src/features/routes/routes.js
Labels: Ready to Merge, enhancement, ready to code review

#223 Course Details Feature
  src/components/tab/tab.js
  src/components/tabs/tabs.js
  src/features/add-course/add-course.js
  src/features/course-details/course-details.js
  src/features/course-details/course-details.scss
  src/features/course-details/index.js
  src/features/edit-course/edit-course.js
  src/features/edit-course/edit-course.scss
  src/features/index.js
  src/features/list-of-courses/list-of-courses.js
  src/features/routes/routes.js
  src/models/courses/actions.js
  src/models/courses/index.js
  src/models/courses/reducer.js
  src/models/courses/reducers/all-courses-reducer.js
  src/models/courses/reducers/create-course-reducer.js
  src/models/courses/reducers/edit-course-reducer.js
  src/models/courses/reducers/index.js
  src/models/courses/selectors.js
  src/models/courses/types.js
  src/screens/courses/courses-tabs.js
  src/screens/courses/index.js
  src/screens/index.js
Labels: Ready to Merge, enhancement, ready to code review

#237 Rusynov 206 connect model to list of groups
  .eslintrc.js
  config/webpack.dev.js
  config/webpack.prod.js
  package-lock.json
  package.json
  src/app.js
  src/features/add-lesson/add-lesson.js
  src/features/edit-lesson/edit-lesson.js
  src/features/list-of-groups/groups.js
  src/features/list-of-groups/list-of-groups.js
  src/features/list-of-groups/list-of-groups.scss
  src/features/list-of-mentors/mentors-dataList.js
  src/features/routes/routes.js
  src/index.html
  src/models/student-groups/reducer.js
Labels: Ready to Merge, enhancement, ready to code review

#219 Authorization feature
  src/components/button/button.js
  src/features/auth/auth.js
  src/features/routes/routes.js
  src/features/validation/validation-helpers.js
  src/models/account/reducers/login-reducer.js
  src/shared/api-service/api-service.js
  src/shared/api-service/config.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#230 Drozdov 197 connect list of secretaries to model
  src/components/card/card.js
  src/features/list-of-secretaries/list-of-secretaries.js
  src/features/list-of-secretaries/redux/action-types.js
  src/features/list-of-secretaries/redux/actions.js
  src/features/list-of-secretaries/redux/index.js
  src/features/list-of-secretaries/redux/reducer.js
  src/features/list-of-secretaries/redux/selectors.js
  src/features/list-of-secretaries/secretariesData.js
  src/features/routes/routes.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#235 Drozdov 232 secretarys details
  src/components/tabs/tabs.js
  src/features/index.js
  src/features/list-of-secretaries/list-of-secretaries.js
  src/features/routes/routes.js
  src/features/secretarys-details/index.js
  src/features/secretarys-details/secretarys-details.js
  src/features/secretarys-details/secretarys-details.scss
  src/models/secretary/index.js
  src/screens/index.js
  src/screens/secretaries/index.js
  src/screens/secretaries/secretaries-tabs.js
Labels: enhancement

#251 Fix bugs
  src/features/add-course/add-course.js
  src/features/course-details/course-details.js
  src/features/edit-course/edit-course.js
Labels: enhancement

#266 Split Lessons Reducer
  src/models/lessons/actions.js
  src/models/lessons/index.js
  src/models/lessons/reducer.js
  src/models/lessons/reducers/add-lesson-reducer.js
  src/models/lessons/reducers/all-lessons-reducer.js
  src/models/lessons/reducers/edit-lesson-reducer.js
  src/models/lessons/selectors.js
Labels: enhancement, ready to code review

#211 Connect lessons list to model
  src/features/list-of-lessons/lessons-dataList.js
  src/features/list-of-lessons/list-of-lessons.js
  src/features/list-of-lessons/list-of-lessons.scss
  src/features/routes/helpers.js
  src/features/routes/routes.js
  src/models/index.js
  src/models/lessons/reducer.js
  src/models/lessons/reducers/index.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#246 Add Lesson Feature
  package-lock.json
  src/app.js
  src/features/add-course/add-course.js
  src/features/add-lesson/add-lesson.js
  src/features/add-lesson/add-lesson.scss
  src/features/edit-mentor/edit-mentor.js
  src/features/edit-students-details/edit-students-details.js
  src/features/index.js
  src/features/list-of-groups/list-of-groups.js
  src/features/list-of-groups/list-of-groups.scss
  src/features/routes/helpers.js
  src/features/routes/routes.js
  src/models/lessons/action-types.js
  src/models/lessons/actions.js
  src/models/lessons/reducers/add-lesson-reducer.js
  src/models/lessons/reducers/all-lessons-reducer.js
  src/models/lessons/reducers/edit-lesson-reducer.js
  src/models/mentors/index.js
  src/models/mentors/reducer.js
  src/models/mentors/selectors.js
  src/models/students/index.js
  src/root-saga.js
  src/shared/api-service/config.js
Labels: enhancement, ready to code review

#259 Replaced BrowserRouter import to HashRouter
  src/index.js
Labels: enhancement, ready to code review

#270 Split themes reducer
  src/models/themes/actions.js
  src/models/themes/index.js
  src/models/themes/reducer.js
  src/models/themes/reducers/all-themes-reducer.js
  src/models/themes/reducers/create-theme-reducer.js
  src/models/themes/reducers/delete-theme-reducer.js
  src/models/themes/reducers/edit-theme-reducer.js
  src/models/themes/reducers/index.js
  src/models/themes/selectors.js
  src/models/themes/types.js
Labels: enhancement, ready to code review

#274 Split schedules reducer
  src/models/schedules/actions.js
  src/models/schedules/index.js
  src/models/schedules/reducer.js
  src/models/schedules/reducers/all-schedules-reducer.js
  src/models/schedules/reducers/create-schedule-reducer.js
  src/models/schedules/reducers/delete-schedule-reducer.js
  src/models/schedules/reducers/edit-schedule-reducer.js
  src/models/schedules/reducers/index.js
  src/models/schedules/reducers/schedule-by-group-id-reducer.js
  src/models/schedules/selectors.js
  src/models/schedules/types.js
Labels: enhancement, ready to code review

#267 Add a model Mentor details
  src/app.js
  src/features/edit-mentor/edit-mentor.js
  src/features/index.js
  src/features/list-of-mentors/list-of-mentors.js
  src/features/mentor-details/index.js
  src/features/mentor-details/mentor-details.js
  src/features/routes/routes.js
  src/features/validation/validation-helpers.js
  src/screens/index.js
  src/screens/mentors/index.js
  src/screens/mentors/mentor-tabs.js
  src/shared/api-service/config.js
Labels: Ready to Merge, Resolve Conflicts

#247 Edit student details Feature
  src/features/courses/add-course/add-course.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/list-of-mentors/list-of-mentors.scss
  src/features/routes/routes.js
  src/features/students/edit-students-details/edit-students-details.js
  src/features/students/edit-students-details/edit-students-details.scss
  src/features/students/list-of-students/list-of-students.js
  src/features/validation/validation-helpers.js
  src/index.js
  src/models/student-groups/actions.js
  src/models/student-groups/index.js
  src/models/student-groups/reducer.js
  src/models/student-groups/reducers/add-group-reducer.js
  src/models/student-groups/reducers/edit-group-reducer.js
  src/models/student-groups/reducers/index.js
  src/models/student-groups/reducers/load-group-by-id-reducer.js
  src/models/student-groups/reducers/load-groups-reducer.js
  src/models/student-groups/selector.js
  src/models/students/action-types.js
  src/models/students/actions.js
  src/models/students/index.js
  src/models/students/reducers/edit-student-reducer.js
  src/models/students/reducers/remove-student-reducer.js
  src/screens/groups/groups-tabs.js
  src/screens/index.js
  src/screens/students/index.js
  src/screens/students/students-tabs.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#234 Protected route component
  src/app.js
  src/components/index.js
  src/components/protected-route/index.js
  src/components/protected-route/protected-route.js
  src/features/auth/auth.js
  src/features/courses/add-course/add-course.js
  src/features/courses/course-details/course-details.js
  src/features/courses/edit-course/edit-course.js
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/groups/group-details/group-details.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/index.js
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/mentor-details/mentor-details.js
  src/features/not-found/not-found.js
  src/features/routes/helpers.js
  src/features/routes/index.js
  src/features/routes/routes.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/shared/constants/index.js
  src/features/shared/constants/proptypes-shapes.js
  src/features/shared/index.js
  src/features/students/edit-students-details/edit-students-details.js
  src/features/students/list-of-students/list-of-students.js
  src/models/secretary/index.js
  src/screens/courses/courses-tabs.js
  src/screens/groups/groups-tabs.js
  src/screens/secretaries/secretaries-tabs.js
  src/shared/constants/index.js
  src/shared/index.js
  src/shared/routes/index.js
  src/shared/routes/paths.js
  src/shared/routes/routes.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#257 Drozdov 209 edit secretarys details to model
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.scss
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/secretarys-details/secretarys-details.js
  src/models/secretary/action-types.js
  src/models/secretary/actions.js
  src/models/secretary/index.js
  src/models/secretary/reducer.js
  src/models/secretary/reducers/all-secretaries-reducer.js
  src/models/secretary/reducers/create-secretary-reducer.js
  src/models/secretary/reducers/delete-secretary-reducer.js
  src/models/secretary/reducers/index.js
  src/models/secretary/reducers/update-secretary-reducer.js
  src/models/secretary/selectors.js
  src/screens/secretaries/secretaries-tabs.js
  src/shared/api-service/config.js
  src/shared/routes/paths.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#263 Student details feature
  src/features/index.js
  src/features/students/edit-students-details/edit-students-details.js
  src/features/students/index.js
  src/features/students/list-of-students/list-of-students.js
  src/features/students/student-details/index.js
  src/features/students/student-details/student-details.js
  src/features/students/student-details/student-details.scss
  src/features/validation/validation-helpers.js
  src/models/students/reducers/current-student-reducer.js
  src/screens/students/students-tabs.js
  src/shared/routes/routes.js
Labels: Ready to Merge, enhancement, ready to code review

#261 Connect model to edit group
  src/components/button/button.js
  src/features/groups/edit-group/edit-group.js
  src/features/groups/edit-group/edit-groups.scss
  src/features/groups/group-details/group-details.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/shared/constants/proptypes-shapes.js
  src/models/student-groups/action-types.js
  src/models/student-groups/actions.js
  src/models/student-groups/reducers/edit-group-reducer.js
  src/models/student-groups/reducers/load-group-by-id-reducer.js
  src/models/student-groups/selector.js
  src/screens/groups/groups-tabs.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#275 Layout feature
  src/features/counter/counter.js
  src/features/index.js
  src/features/layout/index.js
  src/features/layout/layout.js
  src/features/layout/layout.scss
  src/features/layout/redux/action-types.js
  src/features/layout/redux/actions.js
  src/features/layout/redux/index.js
  src/features/layout/redux/reducer.js
  src/features/layout/redux/selectors.js
  src/reducer.js
  src/root-saga.js
  src/shared/routes/routes.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#276 Pasternak 273 bug fix add role list
  src/features/unassigned-list/unassigned-list.js
  src/features/unassigned-list/unassigned-list.scss
  src/models/account/reducers/unassigned-reducer.js
Labels: bug, ready to code review

#293 Fix group edit
  src/components/tabs/tabs.js
  src/features/auth/auth.js
  src/features/counter/counter.js
  src/features/groups/edit-group/edit-group.js
  src/features/groups/group-details/group-details.js
Labels: enhancement, ready to code review

#258 Split groups reducer
  src/features/groups/edit-group/edit-group.js
  src/features/lessons/add-lesson/add-lesson.js
  src/models/student-groups/actions.js
  src/models/student-groups/index.js
  src/models/student-groups/reducers/add-group-reducer.js
  src/models/student-groups/reducers/edit-group-reducer.js
  src/models/student-groups/reducers/load-group-by-id-reducer.js
  src/models/student-groups/reducers/load-groups-reducer.js
  src/models/student-groups/selector.js
  src/screens/groups/groups-tabs.js
Labels: Ready to Merge, Resolve Conflicts, hot, ready to code review

#292 Proper header according to the specific role
  src/assets/svg/Profile.svg
  src/features/header/header.js
  src/features/header/header.scss
  src/features/layout/layout.js
  src/features/lessons/add-lesson/add-lesson.js
  src/shared/routes/paths.js
Labels: enhancement, hot, ready to code review

#284 Modal window for excluding student
  src/features/modal-window/modal-window.scss
  src/features/students/edit-students-details/edit-students-details.js
Labels: enhancement, ready to code review

#280 Registration feature
  src/features/auth/auth.js
  src/features/auth/auth.scss
  src/features/counter/counter.js
  src/features/index.js
  src/features/registration/index.js
  src/features/registration/registration.js
  src/features/registration/registration.scss
  src/features/registration/successful-registration-alert.js
  src/features/students/edit-students-details/edit-students-details.js
  src/features/students/student-details/student-details.js
  src/features/unassigned-list/unassigned-list.js
  src/features/validation/form-example.js
  src/features/validation/index.js
  src/models/account/index.js
  src/models/account/reducer.js
  src/models/account/reducers/index.js
  src/models/account/reducers/login-reducer.js
  src/models/account/reducers/regist-reducer.js
  src/models/account/reducers/unassigned-reducer.js
  src/models/account/reducers/user-list-reducer.js
  src/models/account/sagas.js
  src/models/account/selectors.js
  src/models/account/types.js
  src/shared/routes/routes.js
Labels: enhancement, hot, ready to code review

#294 Edit Lesson Feature
  src/features/layout/layout.js
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/add-lesson/add-lesson.scss
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/lessons/edit-lesson/edit-lesson.scss
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#304 Fix edit mentor
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
  src/features/header/header.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/mentors/edit-mentor/edit-mentor.scss
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/list-of-mentors/list-of-mentors.scss
  src/features/routes/routes.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.scss
  src/models/mentors/actions.js
  src/models/mentors/reducer.js
  src/models/mentors/reducers/mentor-edit.js
  src/screens/mentors/mentor-tabs.js
Labels: Ready to Merge, Resolve Conflicts

#298 Fix common styles for all Lists
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/list-of-mentors/list-of-mentors.scss
  src/features/routes/routes.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.scss
  src/features/students/list-of-students/list-of-students.js
  src/features/students/list-of-students/list-of-students.scss
  src/features/unassigned-list/unassigned-list.js
  src/features/unassigned-list/unassigned-list.scss
Labels: Ready to Merge, Resolve Conflicts

#308 Fix Cards
  src/components/card/card.scss
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/mentor-details/mentor-details.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/secretarys-details/secretarys-details.js
  src/features/students/list-of-students/list-of-students.js
  src/features/students/student-details/student-details.js
Labels: bug, ready to code review

#305 Pagination
  src/components/index.js
  src/components/pagination/index.js
  src/components/pagination/pagination.js
  src/components/pagination/pagination.scss
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/students/list-of-students/list-of-students.js
Labels: enhancement, ready to code review

#307 Fix header component styles
  src/features/header/header.scss
Labels: enhancement, ready to code review

#316 Fix Student Ids
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/edit-lesson/edit-lesson.js
  src/shared/api-service/config.js
Labels: bug, ready to code review

#310 Add links in details components
  src/features/groups/group-details/group-details.js
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/students/student-details/student-details.js
Labels: enhancement, ready to code review

#319 Fix header active tabs
  src/features/header/header.js
Labels: bug, ready to code review

#338 Fixed active mentors in group details
  src/screens/groups/groups-tabs.js
Labels: bug, ready to code review

#337 Fix header
  src/features/header/header.js
Labels: bug, ready to code review
