Repository ita-social-projects/what-front, pull requests merged in 2021-10, with the labels that each got.

#763 add prettier-plugin
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
Labels: enhancement

#746 Resolve #681, added unit-tests for edit course component
  src/features/courses/edit-course/__tests__/edit-course.test.js
Labels: Unit-tests

#745 Resolve #678 added unit-tests for edit-secretaries-details component
  src/features/secretaries/edit-secretarys-details/__mocks__/mockedData.js
  src/features/secretaries/edit-secretarys-details/__tests__/edit-secretarys-details.test.js
Labels: Unit-tests

#734 test(registration): add unit-test for registration component
  src/features/registration/__tests__/__snapshots__/registration.test.js.snap
  src/features/registration/__tests__/registration.test.js
Labels: Unit-tests

#740 Resolve #738 User with role of Secretary can sign in to the site.
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/layout/layout.js
  src/features/lessons/list-of-lessons/list-of-lessons-old.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/schedule/schedule-base/schedule.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/secretarys-details/secretarys-details.js
  src/features/sidebar/sidebar.js
  src/features/students/list-of-students/list-of-students.js
  src/screens/courses/courses-tabs.js
  src/shared/routes/paths.js
  src/shared/routes/routes.js
Labels: Resolve Conflicts

#761 Frakiants 750 add storybook
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/button/button.stories.js
  src/components/card/card.stories.js
  src/components/search/search.stories.js
  src/components/tab/tab.stories.js
Labels: enhancement, Resolve Conflicts

#796 #786 fix layout with buttons upload and add students
  src/features/students/list-of-students/list-of-students.js
Labels: fix
