Repository ita-social-projects/what-front, pull requests merged in 2021-12, with the labels that each got.

#866 fix table word break
  src/components/table/table.js
  src/components/table/table.scss
Labels: fix

#864 feat(export): add export model
  src/models/export/actions.js
  src/models/export/index.js
  src/models/export/reducer.js
  src/models/export/reducers/group-results-reducer.js
  src/models/export/reducers/index.js
  src/models/export/reducers/student-classbook-reducer.js
  src/models/export/reducers/student-results-reducer.js
  src/models/export/reducers/students-classbook-reducer.js
  src/models/export/reducers/students-results-reducer.js
  src/models/export/selectors.js
  src/models/export/types.js
  src/models/index.js
  src/reducer.js
  src/root-saga.js
Labels: enhancement

#820 tests(download students): add tests for download students component
  .eslintrc.js
  package.json
  src/features/students/download-students/__tests__/__snapshots__/download-students.test.js.snap
  src/features/students/download-students/__tests__/download-students.test.js
  src/features/students/download-students/mocks/mock-data.js
  src/features/students/download-students/mocks/mock-file.xlsx
Labels: Unit-tests

#870 feat(students): fix students buttons markup
  src/features/students/list-of-students/list-of-students.js
  src/features/students/list-of-students/list-of-students.scss
Labels: fix

#878 [api] base url is updated
  src/features/schedule/add-schedule/add-schedule.scss
  src/shared/api-service/config.js
Labels: fix

#880 feat(export): change the names of global variables
  src/models/export/actions.js
  src/models/export/index.js
  src/models/export/selectors.js
Labels: fix

#881 tests(course-details): add unit tests for course-details component (#…
  src/features/courses/course-details/__test__/__snapshots__/course-details.test.js.snap
  src/features/courses/course-details/__test__/course-details.test.js
Labels: Unit-tests

#862 add homeworkStudent model
  src/models/homework-student/actions.js
  src/models/homework-student/index.js
  src/models/homework-student/reducer.js
  src/models/homework-student/reducers/add-homework-student-reducer.js
  src/models/homework-student/reducers/get-by-id-homework-student-reducer.js
  src/models/homework-student/reducers/get-homework-student-reducer.js
  src/models/homework-student/reducers/index.js
  src/models/homework-student/reducers/update-homework-student-reducer.js
  src/models/homework-student/selectors.js
  src/models/homework-student/types.js
  src/root-saga.js
Labels: Resolve Conflicts
