Repository ita-social-projects/what-front, pull requests merged in 2021-01, with the labels that each got.

#339 Dashboard Model
  src/features/counter/counter.js
  src/models/dashboard/actions.js
  src/models/dashboard/index.js
  src/models/dashboard/reducer.js
  src/models/dashboard/reducers/group-results-reducer.js
  src/models/dashboard/reducers/index.js
  src/models/dashboard/reducers/student-classbook-reducer.js
  src/models/dashboard/reducers/student-results-reducer.js
  src/models/dashboard/reducers/students-classbook-reducer.js
  src/models/dashboard/reducers/students-results-reducer.js
  src/models/dashboard/selectors.js
  src/models/dashboard/types.js
  src/models/index.js
  src/models/mentors/actions.js
  src/reducer.js
  src/root-saga.js
Labels: enhancement, ready to code review

#312 Fix edit components
  src/features/auth/auth.js
  src/features/courses/add-course/add-course.js
  src/features/courses/edit-course/edit-course.js
  src/features/groups/edit-group/edit-group.js
  src/features/lessons/add-lesson/add-lesson.js
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/registration/registration.js
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
  src/features/students/edit-students-details/edit-students-details.js
  src/features/validation/validation-helpers.js
Labels: enhancement

#306 Fix Add/Edit Lesson
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/add-lesson/add-lesson.scss
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/lessons/edit-lesson/edit-lesson.scss
Labels: enhancement, ready to code review

#322 Sorting for lessons and groups
  src/features/auth/auth.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
Labels: enhancement, ready to code review

#333 Fix unassigned list
  src/features/unassigned-list/unassigned-list.js
  src/features/unassigned-list/unassigned-list.scss
Labels: fix

#340 Updated lessons model + student`s details
  src/features/students/student-details/student-details.js
  src/models/lessons/action-types.js
  src/models/lessons/actions.js
  src/models/lessons/index.js
  src/models/lessons/reducer.js
  src/models/lessons/reducers/index.js
  src/models/lessons/reducers/student-lessons-reducer.js
  src/models/lessons/selectors.js
  src/screens/students/students-tabs.js
Labels: enhancement, ready to code review

#349 Fix homepage redirecting
  src/features/layout/layout.js
Labels: fix

#334 Role check for components
  src/features/courses/course-details/course-details.js
  src/features/courses/course-details/course-details.scss
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
  src/features/header/header.js
  src/features/layout/layout.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/mentor-details/mentor-details.js
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.scss
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/secretarys-details/secretarys-details.js
  src/features/secretaries/secretarys-details/secretarys-details.scss
  src/features/students/list-of-students/list-of-students.js
  src/screens/courses/courses-tabs.js
  src/screens/mentors/mentor-tabs.js
  src/screens/secretaries/secretaries-tabs.js
Labels: Ready to Merge, enhancement, ready to code review

#344 Lesson details component
  src/assets/svg/Absent.svg
  src/assets/svg/Present.svg
  src/features/groups/group-details/group-details.js
  src/features/header/header.js
  src/features/layout/layout.js
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/lessons/edit-lesson/edit-lesson.scss
  src/features/lessons/index.js
  src/features/lessons/lesson-details/index.js
  src/features/lessons/lesson-details/lesson-details.js
  src/features/lessons/lesson-details/lesson-details.scss
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
  src/features/schedule-student/index.js
  src/features/schedule-student/schedule.js
  src/features/schedule-student/schedule.scss
  src/features/students/student-details/student-details.js
  src/shared/routes/paths.js
Labels: Ready to Merge, enhancement, ready to code review

#318 Schedule feat
  src/assets/svg/Arrow.svg
  src/features/index.js
  src/features/layout/layout.js
  src/features/schedule-student/index.js
  src/features/schedule-student/schedule.js
  src/features/schedule-student/schedule.scss
  src/features/schedule/index.js
  src/features/schedule/schedule.js
  src/features/schedule/schedule.scss
  src/shared/api-service/config.js
  src/shared/routes/paths.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#348 Import model
  src/models/import/actions.js
  src/models/import/index.js
  src/models/import/reducer.js
  src/models/import/reducers/groups-reducer.js
  src/models/import/reducers/index.js
  src/models/import/reducers/students-reducer.js
  src/models/import/reducers/themes-reducer.js
  src/models/import/selectors.js
  src/models/import/types.js
  src/models/index.js
  src/reducer.js
  src/root-saga.js
Labels: enhancement, ready to code review

#355 Rusynov 346 prepare deploy
  config/paths.js
  config/webpack.common.js
  config/webpack.dev.js
  config/webpack.prod.js
  package-lock.json
  package.json
  public/404.html
  public/favicon-32x32.png
  public/manifest.json
  public/maskable-512x512.png
Labels: Ready to Merge

#357 Fix mentors unassigned list
  src/features/layout/layout.js
Labels: bug, ready to code review

#351 Fix my profile
  src/features/my-profile/my-profile.js
  src/features/my-profile/my-profile.scss
  src/models/account/sagas.js
Labels: bug, ready to code review

#342 Change password feature
  src/features/change-password/change-password.js
  src/features/change-password/change-password.scss
  src/features/change-password/index.js
  src/features/index.js
  src/features/layout/layout.js
  src/features/my-profile/my-profile.js
  src/features/routes/routes.js
  src/features/validation/validation-helpers.js
  src/models/account/index.js
  src/models/account/reducer.js
  src/models/account/reducers/change-password.js
  src/models/account/reducers/index.js
  src/models/account/sagas.js
  src/models/account/selectors.js
  src/models/account/types.js
  src/shared/api-service/config.js
  src/shared/routes/paths.js
Labels: Ready to Merge, enhancement

#363 Fixed header tabs
  src/features/header/header.js
Labels: bug, ready to code review

#359 Fixed users possibilities
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/layout/layout.js
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/students/student-details/student-details.js
Labels: bug, ready to code review

#369 Fixed lesson details
  src/features/lessons/lesson-details/lesson-details.js
Labels: bug, ready to code review

#380 Fixed styles
  src/components/card/card.js
  src/components/card/card.scss
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/students/list-of-students/list-of-students.js
  src/styles/_helpers.scss
Labels: enhancement, ready to code review

#393 Updated list of groups
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
Labels: enhancement, ready to code review

#385 Updated pagination component
  src/components/pagination/pagination.js
  src/components/pagination/pagination.scss
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/students/list-of-students/list-of-students.js
Labels: enhancement, ready to code review

#382 Error interceptor
  src/features/auth/auth.js
  src/models/account/reducers/change-password.js
  src/models/account/sagas.js
  src/models/courses/actions.js
  src/models/dashboard/actions.js
  src/models/import/actions.js
  src/models/lessons/actions.js
  src/models/mentors/actions.js
  src/models/mentors/reducers/mentor-add.js
  src/models/mentors/reducers/mentor-courses.js
  src/models/mentors/reducers/mentor-current.js
  src/models/mentors/reducers/mentor-delete.js
  src/models/mentors/reducers/mentor-edit.js
  src/models/mentors/reducers/mentor-groups.js
  src/models/mentors/reducers/mentors-active.js
  src/models/mentors/reducers/mentors-all.js
  src/models/schedules/actions.js
  src/models/secretary/reducers/all-secretaries-reducer.js
  src/models/secretary/reducers/create-secretary-reducer.js
  src/models/secretary/reducers/delete-secretary-reducer.js
  src/models/secretary/reducers/update-secretary-reducer.js
  src/models/student-groups/actions.js
  src/models/student-groups/reducers/add-group-reducer.js
  src/models/student-groups/reducers/edit-group-reducer.js
  src/models/student-groups/reducers/load-group-by-id-reducer.js
  src/models/student-groups/reducers/load-groups-reducer.js
  src/models/students/actions.js
  src/models/students/reducers/active-students-reducer.js
  src/models/students/reducers/add-student-reducer.js
  src/models/students/reducers/all-students-reducer.js
  src/models/students/reducers/current-student-groups-reducer.js
  src/models/students/reducers/current-student-reducer.js
  src/models/students/reducers/edit-student-reducer.js
  src/models/students/reducers/remove-student-reducer.js
  src/models/themes/actions.js
  src/shared/api-service/api-service.js
  src/shared/api-service/interceptors.js
Labels: enhancement, ready to code review

#352 Attachments model added
  src/models/attachments/actions.js
  src/models/attachments/index.js
  src/models/attachments/reducer.js
  src/models/attachments/reducers/attachment-current.js
  src/models/attachments/reducers/attachments-all-add.js
  src/models/attachments/reducers/attachments-all.js
  src/models/attachments/reducers/index.js
  src/models/attachments/selectors.js
  src/models/attachments/types.js
  src/models/index.js
  src/reducer.js
  src/root-saga.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#391 Mentor details extended
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/mentors/mentor-details/mentor-details.js
Labels: Ready to Merge, enhancement, ready to code review

#394 fix: webpack prebuild messages & prune gh-pages dep
  config/webpack.dev.js
  config/webpack.prod.js
  package-lock.json
  package.json
Labels: fix

#364 Add alerts for user actions
  src/features/alert-box/alert-box.js
  src/features/alert-box/alert-box.scss
  src/features/alert-box/index.js
  src/features/alert-box/redux/action-types.js
  src/features/alert-box/redux/actions.js
  src/features/alert-box/redux/index.js
  src/features/alert-box/redux/reducer.js
  src/features/alert-box/redux/selectors.js
  src/features/courses/add-course/add-course.js
  src/features/courses/course-details/course-details.js
  src/features/courses/edit-course/edit-course.js
  src/features/groups/edit-group/edit-group.js
  src/features/index.js
  src/features/layout/index.js
  src/features/layout/layout.js
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
  src/features/students/edit-students-details/edit-students-details.js
  src/features/unassigned-list/unassigned-list.js
  src/models/courses/actions.js
  src/models/courses/reducers/edit-course-reducer.js
  src/models/courses/types.js
  src/models/lessons/action-types.js
  src/models/lessons/actions.js
  src/models/lessons/reducers/add-lesson-reducer.js
  src/models/lessons/reducers/edit-lesson-reducer.js
  src/models/mentors/actions.js
  src/models/mentors/reducers/mentor-edit.js
  src/models/mentors/types.js
  src/models/secretary/action-types.js
  src/models/secretary/actions.js
  src/models/secretary/reducers/update-secretary-reducer.js
  src/models/student-groups/action-types.js
  src/models/student-groups/actions.js
  src/models/student-groups/reducers/edit-group-reducer.js
  src/models/students/action-types.js
  src/models/students/actions.js
  src/models/students/reducers/edit-student-reducer.js
  src/screens/courses/courses-tabs.js
  src/screens/groups/groups-tabs.js
  src/screens/students/students-tabs.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#411 fixed students and mentors data
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/lessons/lesson-details/lesson-details.js
Labels: bug, ready to code review

#414 FIxed loaders
  src/features/courses/course-details/course-details.js
  src/features/groups/edit-group/edit-group.js
  src/features/groups/group-details/group-details.js
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/mentors/mentor-details/mentor-details.js
  src/features/students/edit-students-details/edit-students-details.js
  src/features/students/student-details/student-details.js
Labels: enhancement, ready to code review

#406 Validation fix
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/validation/validation-helpers.js
Labels: ready to code review

#401 Changing values of variables
  src/components/card/card.scss
  src/components/search/search.scss
  src/components/tab/tab.scss
  src/features/change-password/change-password.scss
  src/features/counter/button.scss
  src/features/lessons/add-lesson/add-lesson.scss
  src/features/lessons/edit-lesson/edit-lesson.scss
  src/features/lessons/lesson-details/lesson-details.scss
  src/features/mentors/edit-mentor/edit-mentor.scss
  src/features/modal-window/modal-window.scss
  src/features/my-profile/my-profile.scss
  src/features/registration/registration.scss
  src/features/schedule/schedule.scss
  src/features/students/edit-students-details/edit-students-details.scss
  src/features/unassigned-list/unassigned-list.scss
  src/styles/_color-palette.scss
  src/styles/_fonts.scss
  src/styles/_helpers.scss
  src/styles/_sizes.scss
  src/styles/_theme.scss
  src/styles/_variables.scss
Labels: ready to code review

#402 Default sorting by last name
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/students/list-of-students/list-of-students.js
Labels: ready to code review

#423 Minor fixes
  src/features/students/student-details/student-details.js
  src/features/validation/validation-helpers.js
  src/shared/api-service/config.js
Labels: bug, ready to code review

#424 Fix header active tabs
  src/features/header/header.js
  src/features/lessons/lesson-details/lesson-details.js
  src/features/mentors/mentor-details/mentor-details.js
Labels: bug, ready to code review

#422 feat: set css treeshacking
  config/paths.js
  config/webpack.prod.js
  package-lock.json
  package.json
Labels: enhancement, ready to code review

#420 Fix error interceptor
  src/features/courses/course-details/course-details.js
  src/models/courses/actions.js
  src/shared/api-service/config.js
  src/shared/api-service/interceptors.js
Labels: fix

#415 Update change password feature
  src/features/change-password/change-password.js
  src/models/account/reducers/change-password.js
  src/models/account/sagas.js
Labels: enhancement, ready to code review

#444 Fixed pagination
  src/components/pagination/pagination.js
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/students/list-of-students/list-of-students.js
Labels: bug, fix, ready to code review

#445 Аdd group starting
  src/features/groups/start-group/start-group.js
  src/features/groups/start-group/start-group.scss
  src/features/layout/layout.js
  src/models/student-groups/action-types.js
  src/models/student-groups/actions.js
  src/models/student-groups/reducers/add-group-reducer.js
Labels: enhancement, ready to code review

#438 Change header component. Added dropdown menu.
  src/features/header/header.js
  src/features/header/header.scss
  src/features/students/student-details/student-details.js
  src/shared/api-service/config.js
Labels: Ready to Merge, enhancement, ready to code review

#448 Fixed add lesson bug
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/validation/validation-helpers.js
Labels: bug, fix, ready to code review

#441 feat: redesign 404 error
  src/features/not-found/not-found.js
  src/features/not-found/not-found.scss
Labels: enhancement, ready to code review

#447 Redesign list of mentors
  src/components/pagination/pagination.js
  src/components/pagination/pagination.scss
  src/components/search/search.js
  src/features/mentors/list-of-mentors/list-of-mentors-old.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/list-of-mentors/list-of-mentors.scss
  src/styles/_color-palette.scss
Labels: enhancement, ready to code review

#398 Schedule group
  src/assets/svg/Arrow.svg
  src/features/groups/group-details/group-details.js
  src/features/header/header.js
  src/features/layout/layout.js
  src/features/schedule/index.js
  src/features/schedule/schedule-base/index.js
  src/features/schedule/schedule-base/schedule.js
  src/features/schedule/schedule-base/schedule.scss
  src/features/schedule/schedule-group/index.js
  src/features/schedule/schedule-group/shedule-group.js
  src/features/schedule/shedule-all/index.js
  src/features/schedule/shedule-all/schedule-all.js
  src/features/shared/constants/proptypes-shapes.js
  src/features/students/student-details/index.js
  src/models/mentors/actions.js
  src/shared/routes/paths.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#486 WIP : Redesign registration component
  src/features/registration/registration.js
  src/features/registration/registration.scss
  src/features/registration/successful-registration-alert.js
Labels: enhancement, ready to code review

#467 Redesign list of courses
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
Labels: enhancement, ready to code review

#466 Redesign list of secretaries
  README.md
  src/assets/svg/Card.svg
  src/assets/svg/Edit.svg
  src/assets/svg/List.svg
  src/components/pagination/pagination.js
  src/components/search/search.js
  src/components/search/search.scss
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries-cards.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.scss
  src/features/secretaries/secretarys-details/secretarys-details.js
  src/features/validation/validation-helpers.js
  src/screens/secretaries/secretaries-tabs.js
Labels: enhancement, ready to code review

#456 Redesign list of students
  src/assets/svg/Cards.svg
  src/assets/svg/Edit.svg
  src/assets/svg/List.svg
  src/components/button/button.js
  src/components/button/button.scss
  src/components/pagination/pagination.js
  src/components/search/search.js
  src/components/search/search.scss
  src/components/with-loading/with-loading.js
  src/components/with-loading/with-loading.scss
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/students/list-of-students/index.js
  src/features/students/list-of-students/list-of-students-old.js
  src/features/students/list-of-students/list-of-students.js
  src/features/students/list-of-students/list-of-students.scss
  src/shared/api-service/config.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#481 Redesign authorization component
  src/features/auth/auth.js
  src/features/auth/auth.scss
  src/features/registration/registration.js
  src/features/registration/registration.scss
  src/shared/routes/paths.js
Labels: enhancement

#465 Redesign list of groups
  src/features/groups/list-of-groups/list-of-groups-old.js
  src/features/groups/list-of-groups/list-of-groups-old.scss
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
Labels: Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#464 Redesign pagination
  src/assets/svg/Profile.svg
  src/components/pagination/pagination.js
  src/components/pagination/pagination.scss
Labels: enhancement, ready to code review

#478 Redesign groups details and edit
  src/features/groups/edit-group/edit-group.js
  src/features/groups/edit-group/edit-groups.scss
  src/features/groups/group-details/group-details.js
  src/features/groups/group-details/group-details.scss
Labels: enhancement, ready to code review

#480 Redesign tabs
  src/components/tab/tab.scss
  src/components/tabs/tabs.js
  src/styles/_helpers.scss
Labels: enhancement, ready to code review

#483 Redesign courses details and edit
  src/components/button/button.js
  src/features/courses/add-course/add-course.js
  src/features/courses/edit-course/edit-course.js
  src/features/courses/edit-course/edit-course.scss
Labels: enhancement, ready to code review

#458 Redesigned list of lessons added
  src/assets/svg/Card.svg
  src/assets/svg/DropDown.svg
  src/assets/svg/DropDownButton.svg
  src/assets/svg/DropUp.svg
  src/assets/svg/Edit.svg
  src/assets/svg/List.svg
  src/components/pagination/pagination.scss
  src/components/search/search.js
  src/components/search/search.scss
  src/features/lessons/lesson-details/lesson-details.js
  src/features/lessons/list-of-lessons/list-of-lessons-old.js
  src/features/lessons/list-of-lessons/list-of-lessons-old.scss
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
  src/styles/_helpers.scss
  src/styles/_sizes.scss
  src/styles/_variables.scss
Labels: ready to code review

#485 Redesign mentor's details and edit component
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/mentors/edit-mentor/edit-mentor.scss
  src/features/mentors/mentor-details/mentor-details.js
Labels: enhancement, ready to code review

#443 Sidebar menu
  package-lock.json
  src/assets/svg/Assigment.svg
  src/assets/svg/Courses.svg
  src/assets/svg/Groups.svg
  src/assets/svg/Lessons.svg
  src/assets/svg/Mentors.svg
  src/assets/svg/Schedule.svg
  src/assets/svg/Secretaries.svg
  src/assets/svg/SidebarToggler.svg
  src/assets/svg/Students.svg
  src/assets/svg/Support.svg
  src/features/header/header.js
  src/features/header/header.scss
  src/features/index.js
  src/features/layout/layout.js
  src/features/sidebar/index.js
  src/features/sidebar/sidebar.js
  src/features/sidebar/sidebar.scss
Labels: enhancement, ready to code review

#492 Fix sorting in list of mentors
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/list-of-mentors/list-of-mentors.scss
  src/features/sidebar/sidebar.js
  src/models/mentors/actions.js
  src/models/mentors/reducers/mentor-delete.js
Labels: bug, fix, ready to code review

#484 Redesign secretary's details and edit components
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
Labels: enhancement, ready to code review

#493 Redesign add group
  src/features/groups/start-group/start-group.js
  src/features/layout/layout.js
  src/features/layout/layout.scss
  src/features/sidebar/sidebar.js
  src/features/sidebar/sidebar.scss
Labels: fix, ready to code review

#488 Redesign shedule
  src/features/schedule/schedule-base/schedule.js
  src/features/schedule/schedule-base/schedule.scss
Labels: enhancement, ready to code review

#494 Fix styles control bars
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/list-of-mentors/list-of-mentors.scss
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.scss
  src/features/students/list-of-students/list-of-students.js
  src/features/students/list-of-students/list-of-students.scss
  src/styles/_helpers.scss
Labels: fix

#479 Redesign students details and edit components
  src/features/students/edit-students-details/edit-students-details.js
  src/features/students/edit-students-details/edit-students-details.scss
  src/features/students/student-details/student-details.js
Labels: enhancement, ready to code review

#498 Redesign change password
  src/features/change-password/change-password.js
  src/features/change-password/change-password.scss
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/my-profile/my-profile.js
  src/features/my-profile/my-profile.scss
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
Labels: enhancement

#497 Fix authorisation and registration
  src/features/auth/auth.js
  src/features/registration/registration.js
Labels: bug, fix

#499 Hotfixes
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
  src/features/lessons/lesson-details/lesson-details.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/sidebar/sidebar.js
  src/features/students/list-of-students/list-of-students.scss
Labels: bug, fix, hot
