Repository ita-social-projects/what-front, pull requests merged in 2021-06, with the labels that each got.

#663 unit tests for studentLessonDetails component
  src/features/lessons/student-lesson-details/__tests__/student-lesson-details.test.js
  src/features/lessons/student-lesson-details/student-lesson-details.js
Labels: Unit-tests

#662 Kryvosheia #528 layout moving with open sidebar
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/groups/download-groups/download-groups.js
  src/features/groups/group-details/group-details.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/layout/layout.js
  src/features/layout/layout.scss
  src/features/lessons/lesson-details/lesson-details.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/student-lesson-details/student-lesson-details.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/schedule/schedule-base/schedule.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/sidebar/sidebar.scss
  src/features/students/download-students/download-students.js
  src/features/students/list-of-students/list-of-students.js
  src/features/unassigned-list/unassigned-list.js
  src/screens/courses/courses-tabs.js
  src/screens/groups/groups-tabs.js
  src/screens/homework/homework-tabs.js
  src/screens/mentors/mentor-tabs.js
  src/screens/secretaries/secretaries-tabs.js
  src/screens/students/students-tabs.js
Labels: Resolve Conflicts

#672 #670 Redirect from lesson-list page to add-lesson leads to page 404
  src/features/layout/layout.js
Labels: bug

#652 Bychkov 387 sort group
  src/features/groups/list-of-groups/list-of-groups.js
  src/utils/helpers/common-helpers.js
Labels: Resolve Conflicts

#664 Bychkov 653 filter input refactor
  src/components/double-date-filter/doubleDateFilter.js
  src/components/double-date-filter/index.js
  src/components/index.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
Labels: Resolve Conflicts

#687 Yakymova #666 unit test add lesson
  package-lock.json
  package.json
  src/components/button/button.js
  src/features/lessons/add-lesson/__tests__/add-lesson.test.js
  src/features/lessons/add-lesson/__tests__/mocks/mock-data.js
  src/features/lessons/add-lesson/__tests__/mocks/mock-useState.js
  src/features/lessons/add-lesson/add-lesson.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/mentors/edit-mentor/edit-mentor.js
Labels: Ready to Merge

#701 Yakymova #680 unit tests edit lesson
  src/features/lessons/add-lesson/__tests__/add-lesson.test.js
  src/features/lessons/edit-lesson/__tests__/edit-lesson.test.js
  src/features/lessons/edit-lesson/__tests__/mocks/mock-data.js
  src/features/lessons/edit-lesson/edit-lesson.js
  src/models/lessons/__mocks__/index.js
  src/models/lessons/__mocks__/lessons-mock-data.js
  src/models/lessons/__mocks__/lessons.js
  src/models/lessons/index.js
Labels: 13 points, Unit-tests
