Repository ita-social-projects/what-front, pull requests merged in 2021-11, with the labels that each got.

#842 update(infra): update base url
  src/shared/api-service/config.js
Labels: fix

#798 Matvienko 795 add disabled courses display and recovery option for courses
  src/features/courses/edit-course/edit-course.js
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
  src/features/groups/download-groups/download-groups.js
  src/features/groups/start-group/start-group.js
  src/features/mentors/edit-mentor/edit-mentor.js
  src/models/courses/actions.js
  src/models/courses/index.js
  src/models/courses/reducer.js
  src/models/courses/reducers/active-course-reducer.js
  src/models/courses/reducers/index.js
  src/models/courses/reducers/not-active-course-reducer.js
  src/models/courses/reducers/reactivate-course-reducer.js
  src/models/courses/selectors.js
  src/models/courses/types.js
  src/screens/courses/courses-tabs.js
  src/screens/groups/groups-tabs.js
Labels: Resolve Conflicts

#810 feat(homework): add homework model
  src/models/homework/actions.js
  src/models/homework/index.js
  src/models/homework/reducer.js
  src/models/homework/reducers/add-homework-reducer.js
  src/models/homework/reducers/get-homework-reducer.js
  src/models/homework/reducers/index.js
  src/models/homework/reducers/update-homework-reducer.js
  src/models/homework/selectors.js
  src/models/homework/types.js
  src/models/index.js
  src/reducer.js
Labels: enhancement

#772 added add-schedule component
  src/features/layout/layout.js
  src/features/schedule/add-schedule/add-schedule-data.js
  src/features/schedule/add-schedule/add-schedule-useFetch.js
  src/features/schedule/add-schedule/add-schedule.js
  src/features/schedule/add-schedule/add-schedule.scss
  src/features/schedule/add-schedule/index.js
  src/features/schedule/index.js
  src/features/validation/validation-helpers.js
Labels: Resolve Conflicts

#818 feat(packages): add @testing-library/user-event
  package-lock.json
  package.json
Labels: enhancement

#747 add sorting for block view
  src/features/students/list-of-students/list-of-students.js
Labels: Resolve Conflicts, fix
