Repository ita-social-projects/what-front, pull requests merged in 2021-02, with the labels that each got.

#519 fix list of groups component
  src/features/groups/list-of-groups/list-of-groups.js
  src/models/courses/actions.js
Labels: fix, ready to code review

#516 fix header dropdown
  src/features/header/header.js
  src/features/header/header.scss
Labels: enhancement, ready to code review

#510 Fixed animation of sidebar
  src/features/sidebar/sidebar.js
  src/features/sidebar/sidebar.scss
Labels: fix, ready to code review

#509 Fix change password
  src/features/change-password/change-password.js
  src/features/modal-window/modal-window.js
  src/features/modal-window/modal-window.scss
  src/features/validation/validation-helpers.js
Labels: fix

#502 Fix: 404 is not shown on invalid student ID
  src/features/students/student-details/student-details.js
Labels: fix, ready to code review

#525 Fix disabled buttons in groups/edit
  src/features/groups/edit-group/edit-group.js
Labels: 5 points, bug, fix

#522 Fix sorting in List of Secretaries
  README.md
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
Labels: fix

#508 Fix: active sidebar item is not shown on Roles page
  src/features/sidebar/sidebar.js
  src/shared/api-service/api-service.js
Labels: fix, ready to code review

#517 Changed colors of modal window buttons
  src/features/courses/edit-course/edit-course.js
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
  src/features/students/edit-students-details/edit-students-details.js
  src/models/courses/actions.js
  src/models/secretary/actions.js
  src/models/secretary/reducers/delete-secretary-reducer.js
  src/models/students/actions.js
  src/models/students/reducers/remove-student-reducer.js
Labels: enhancement, ready to code review

#530 change colors according to color palette
  src/features/courses/edit-course/edit-course.js
  src/features/courses/edit-course/edit-course.scss
  src/features/groups/edit-group/edit-group.js
  src/features/groups/edit-group/edit-groups.scss
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/mentors/edit-mentor/edit-mentor.scss
  src/features/students/edit-students-details/edit-students-details.js
Labels: enhancement, ready to code review

#546 fix account dropdown
  src/features/header/header.js
Labels: fix, ready to code review

#526 Modify pagination
  src/assets/svg/DropDownButton.svg
  src/components/button/button.module.scss
  src/components/pagination/pagination.js
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/courses/list-of-courses/list-of-courses.scss
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
  src/features/header/header.module.scss
  src/features/layout/redux/action-types.js
  src/features/layout/redux/actions.js
  src/features/layout/redux/index.js
  src/features/layout/redux/reducer.js
  src/features/layout/redux/selectors.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/list-of-lessons/list-of-lessons.scss
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/list-of-mentors/list-of-mentors.scss
  src/features/modal-window/modal-window.module.scss
  src/features/schedule/schedule.js
  src/features/schedule/schedule.scss
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.scss
  src/features/secretaries/secretarys-details/secretarys-details.scss
  src/features/students/list-of-students/list-of-students.js
  src/features/students/list-of-students/list-of-students.scss
  src/features/students/student-profile/index.js
  src/features/students/student-profile/student-profile.js
  src/features/students/student-profile/student-profile.scss
  src/features/unassigned-list/unassigned-list.js
  src/features/unassigned-list/unassigned-list.scss
  src/features/validation/form-example.js
  src/features/validation/index.js
  src/models/mentors/helper-functions.js
  src/screens/empty-file.txt
  src/shared/constants/index.js
  src/shared/constants/proptypes-shapes.js
  src/svg/Edit.svg
  src/svg/Plus.svg
  src/utils/empty-file.txt
  webpack.config.js
Labels: 8 points, Ready to Merge, Resolve Conflicts, enhancement, ready to code review

#399 WIP:Import themes added
  package-lock.json
  package.json
  src/features/layout/layout.js
  src/features/lessons/index.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/themes/download-themes/download-themes.js
  src/features/lessons/themes/download-themes/download-themes.scss
  src/features/lessons/themes/download-themes/index.js
  src/features/lessons/themes/index.js
  src/shared/routes/paths.js
Labels: Ready to Merge, Resolve Conflicts, enhancement, question

#403 WIP:Import of students
  src/features/groups/start-group/start-group.scss
  src/features/layout/layout.js
  src/features/lessons/themes/download-themes/download-themes.js
  src/features/students/download-students/download-students.js
  src/features/students/download-students/download-students.scss
  src/features/students/download-students/index.js
  src/features/students/index.js
  src/features/students/list-of-students/list-of-students.js
  src/shared/routes/paths.js
Labels: enhancement, question

#541 Forgot password component
  src/features/change-password/change-password.js
  src/features/forgot-password/forgot-password.js
  src/features/forgot-password/forgot-password.scss
  src/features/forgot-password/index.js
  src/features/index.js
  src/features/modal-window/modal-window.js
  src/features/registration/registration.js
  src/features/reset-password/index.js
  src/features/reset-password/reset-password.js
  src/features/reset-password/reset-password.scss
  src/features/validation/validation-helpers.js
  src/models/account/index.js
  src/models/account/reducer.js
  src/models/account/reducers/forgot-password.js
  src/models/account/reducers/index.js
  src/models/account/reducers/reset-password.js
  src/models/account/sagas.js
  src/models/account/selectors.js
  src/models/account/types.js
  src/shared/routes/paths.js
  src/shared/routes/routes.js
Labels: 13 points, enhancement, question, ready to code review

#548 Fix modal window positioning
  src/features/change-password/change-password.js
  src/features/courses/edit-course/edit-course.js
  src/features/mentors/edit-mentor/edit-mentor.js
  src/features/modal-window/modal-window.js
  src/features/modal-window/modal-window.module.scss
  src/features/modal-window/modal-window.scss
  src/features/secretaries/edit-secretarys-details/edit-secretarys-details.js
  src/features/students/edit-students-details/edit-students-details.js
Labels: fix

#540 fix student editing
  src/features/students/edit-students-details/edit-students-details.js
Labels: 5 points, bug, fix

#559 Registration modal window refactoring
  src/features/groups/index.js
  src/features/registration/registration.js
  src/features/registration/registration.scss
  src/features/registration/successful-registration-alert.js
  src/shared/api-service/config.js
Labels: enhancement

#547 Student lessons component
  src/features/layout/layout.js
  src/features/lessons/index.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/lessons/student-lessons/index.js
  src/features/lessons/student-lessons/student-lessons.js
  src/features/lessons/student-lessons/student-lessons.scss
  src/features/sidebar/sidebar.js
  src/shared/routes/paths.js
Labels: 13 points, Ready to Merge, enhancement

#565 fix group
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
  src/shared/api-service/config.js
Labels: fix, ready to code review

#566 homework layout
  src/features/homework/add-homework/add-homework.js
  src/features/homework/add-homework/add-homework.scss
  src/features/homework/add-homework/index.js
  src/features/homework/edit-homework/edit-homework.js
  src/features/homework/edit-homework/edit-homework.scss
  src/features/homework/edit-homework/index.js
  src/features/homework/homework-details/homework-details.js
  src/features/homework/homework-details/homework-details.scss
  src/features/homework/homework-details/index.js
  src/features/homework/index.js
  src/features/index.js
  src/features/layout/layout.js
  src/screens/homework/homework-tabs.js
  src/screens/homework/index.js
  src/screens/index.js
  src/shared/routes/paths.js
Labels: ready to code review

#556 update mentor model
  src/features/counter/counter.js
  src/features/lessons/edit-lesson/edit-lesson.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/models/mentors/actions.js
  src/models/mentors/index.js
  src/models/mentors/reducer.js
  src/models/mentors/reducers/index.js
  src/models/mentors/reducers/mentor-filter-lessons.js
  src/models/mentors/reducers/mentors-lessons.js
  src/models/mentors/selectors.js
  src/models/mentors/types.js
Labels: Ready to Merge, enhancement
