Repository ita-social-projects/what-front, pull requests merged in 2022-02, with the labels that each got.

#907 List of lessons for user(mentor) is loaded
  src/shared/api-service/interceptors.js
Labels: fix

#905 [Unassigned users] searching by name is displayed existing unassigned user in table
  src/features/unassigned-list/unassigned-list.js
Labels: fix

#904 searching by name is displayed existing secretaries in table
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
Labels: fix

#892 list-of-metnotrs and pagination components are refactored
  package-lock.json
  package.json
  src/components/pagination/pagination.js
  src/features/mentors/list-of-mentors/list-of-mentors.js
  src/features/mentors/list-of-mentors/list-of-mentors.scss
  src/features/mentors/list-of-mentors/useFetchMentors.js
Labels: enhancement

#888 feat(groups): fix groups component buttons markup #887
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/groups/list-of-groups/list-of-groups.scss
Labels: fix

#886 tests(group-details): add unit tests for group-details component (#882)
  src/features/groups/group-details/__test__/__mocks__/mockedData.js
  src/features/groups/group-details/__test__/__snapshots__/group-details.test.js.snap
  src/features/groups/group-details/__test__/group-details.test.js
Labels: Unit-tests

#885 872 add unit tests for list of courses component
  src/features/courses/list-of-courses/__tests__/list-of-courses.test.js
  src/features/courses/list-of-courses/__tests__/mocks/mock-data.js
  src/features/courses/list-of-courses/list-of-courses.js
Labels: Unit-tests

#884 resolves #883 instead of the user's first and last name undefined was displayed
  src/features/header/header.js
Labels: fix

#808 resolves #789 list of courses displayed wrong
  src/features/courses/list-of-courses/list-of-courses.js
Labels: fix

#929 [Courses List] refactor list-of-courses-feature
  src/features/courses/list-of-courses/list-of-courses.js
Labels: 5 points

#863 feat(events): add events model
  src/models/events/actions.js
  src/models/events/index.js
  src/models/events/reducer.js
  src/models/events/reducers/connect-event-reducer.js
  src/models/events/reducers/delete-event-reducer.js
  src/models/events/reducers/get-event-reducer.js
  src/models/events/reducers/index.js
  src/models/events/reducers/update-event-reducer.js
  src/models/events/selectors.js
  src/models/events/types.js
  src/models/index.js
  src/reducer.js
  src/root-saga.js
Labels: enhancement, Change Request

#919 Migur 912 list of students] list of secretaries] list of lessons] list of groups] list of courses] unassigned list] double date filter] fix pagination
  src/components/double-date-filter/doubleDateFilter.js
  src/components/pagination/pagination.js
  src/features/courses/list-of-courses/list-of-courses.js
  src/features/groups/list-of-groups/list-of-groups.js
  src/features/lessons/list-of-lessons/list-of-lessons.js
  src/features/secretaries/list-of-secretaries/list-of-secretaries.js
  src/features/students/list-of-students/list-of-students.js
  src/features/unassigned-list/unassigned-list.js
  src/models/events/actions.js
  src/models/events/reducer.js
Labels: Resolve Conflicts, 20 points
